### ISSUE TITLE
it works !!! :)

### ISSUE THREAD

**Issue by GetRektBoy724** [marcost2/ath10k#1]
wow this shit worked well
to turn on monitor mode : 
airmon-ng check kill
airmon-ng start wlan0
.....................................
airodump-ng work perfectly
but packet injection is still not working tho
if you try to do packet injection with "aireplay-ng -9 wlan0" this thing showed up from dmesg : 
[  167.730039] ------------[ cut here ]------------
[  167.730068] WARNING: CPU: 0 PID: 1681 at drivers/net/wireless/ath/ath10k/mac.c:3791 ath10k_mac_tx+0x2e3/0x4b0 [ath10k_core]
[  167.730069] Modules linked in: snd_seq_dummy(E) snd_hrtimer(E) snd_seq(E) snd_seq_device(E) fuse(E) binfmt_misc(E) nls_ascii(E) nls_cp437(E) vfat(E) fat(E) btusb(E) ath10k_pci(E) intel_rapl_msr(E) intel_rapl_common(E) btrtl(E) ath10k_core(E) btbcm(E) uvcvideo(E) x86_pkg_temp_thermal(E) btintel(E) intel_powerclamp(E) bluetooth(E) jitterentropy_rng(E) coretemp(E) ath(E) mac80211(E) snd_soc_skl(E) kvm_intel(E) snd_soc_hdac_hda(E) drbg(E) snd_hda_ext_core(E) ansi_cprng(E) snd_hda_codec_hdmi(E) snd_soc_sst_ipc(E) cfg80211(E) snd_soc_sst_dsp(E) videobuf2_vmalloc(E) videobuf2_memops(E) videobuf2_v4l2(E) snd_soc_acpi_intel_match(E) snd_hda_codec_generic(E) libarc4(E) snd_soc_acpi(E) ecdh_generic(E) ecc(E) snd_soc_core(E) videobuf2_common(E) ledtrig_audio(E) kvm(E) snd_compress(E) videodev(E) snd_hda_intel(E) irqbypass(E) mc(E) snd_intel_dspcfg(E) snd_hda_codec(E) iTCO_wdt(E) intel_pmc_bxt(E) iTCO_vendor_support(E) intel_xhci_usb_role_switch(E) snd_hda_core(E) snd_hwdep(E) snd_pcm(E) rapl(E)
[  167.730116]  intel_cstate(E) snd_timer(E) snd(E) intel_uncore(E) watchdog(E) roles(E) mei_me(E) efi_pstore(E) soundcore(E) sg(E) ideapad_laptop(E) intel_wmi_thunderbolt(E) efivars(E) joydev(E) serio_raw(E) evdev(E) sparse_keymap(E) mei(E) rfkill(E) intel_pch_thermal(E) tpm_crb(E) tpm_tis(E) tpm_tis_core(E) tpm(E) acpi_pad(E) ac(E) wmi_bmof(E) rng_core(E) sunrpc(E) efivarfs(E) ip_tables(E) x_tables(E) autofs4(E) ext4(E) crc16(E) mbcache(E) jbd2(E) crc32c_generic(E) sd_mod(E) t10_pi(E) crc_t10dif(E) sr_mod(E) cdrom(E) crct10dif_generic(E) hid_rmi(E) rmi_core(E) hid_generic(E) crct10dif_pclmul(E) crct10dif_common(E) crc32_pclmul(E) crc32c_intel(E) ghash_clmulni_intel(E) i915(E) i2c_algo_bit(E) ahci(E) libahci(E) drm_kms_helper(E) aesni_intel(E) libaes(E) crypto_simd(E) cec(E) libata(E) r8169(E) realtek(E) xhci_pci(E) i2c_i801(E) cryptd(E) glue_helper(E) libphy(E) i2c_smbus(E) xhci_hcd(E) scsi_mod(E) intel_lpss_pci(E) intel_lpss(E) idma64(E) drm(E) usbcore(E) usb_common(E) wmi(E) i2c_hid(E)
[  167.730174]  button(E) hid(E) battery(E) video(E)
[  167.730183] CPU: 0 PID: 1681 Comm: aireplay-ng Tainted: G            E     5.8.0-kali2-amd64 #1 Debian 5.8.10-1kali1
[  167.730185] Hardware name: my hardware name
[  167.730202] RIP: 0010:ath10k_mac_tx+0x2e3/0x4b0 [ath10k_core]
[  167.730207] Code: 06 66 44 89 50 0a 66 44 89 78 0c e9 9c fe ff ff 48 8b 87 b0 12 00 00 a8 08 0f 85 8d fe ff ff 41 f6 40 38 20 0f 85 82 fe ff ff <0f> 0b 4c 89 c6 4c 89 f7 41 bd f4 fd ff ff e8 4a 17 e7 ff e9 f0 fe
[  167.730209] RSP: 0018:ffffb60c82a679d8 EFLAGS: 00010246
[  167.730212] RAX: 0000000000000042 RBX: 0000000000000000 RCX: 0000000000000000
[  167.730214] RDX: 0000000000000000 RSI: ffff94fdd8342bb0 RDI: ffff94fde3a61e60
[  167.730216] RBP: ffff94fde3a61e60 R08: ffff94fdd7319a00 R09: 0000000000000000
[  167.730218] R10: 0000000000000000 R11: 0000000000000002 R12: ffff94fdd7319a00
[  167.730220] R13: 0000000000000000 R14: ffff94fde3a607c0 R15: ffff94fdd8342bb0
[  167.730223] FS:  00007f16616d6740(0000) GS:ffff94fde6c00000(0000) knlGS:0000000000000000
[  167.730225] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  167.730227] CR2: 00007ffd650bfca8 CR3: 000000025f6fe006 CR4: 00000000003606f0
[  167.730229] Call Trace:
[  167.730242]  ? account_entity_enqueue+0x9c/0xd0
[  167.730259]  ath10k_mac_op_tx+0x119/0x220 [ath10k_core]
[  167.730316]  ieee80211_tx_frags+0x173/0x250 [mac80211]
[  167.730365]  __ieee80211_tx+0x7a/0x130 [mac80211]
[  167.730412]  ieee80211_tx+0xfd/0x140 [mac80211]
[  167.730457]  ieee80211_monitor_start_xmit+0x336/0x630 [mac80211]
[  167.730467]  dev_hard_start_xmit+0x8d/0x1d0
[  167.730473]  __dev_queue_xmit+0x654/0x8c0
[  167.730479]  ? packet_parse_headers+0xd8/0x110
[  167.730485]  packet_sendmsg+0xac1/0x1580
[  167.730490]  ? _cond_resched+0x16/0x40
[  167.730494]  ? aa_sk_perm+0x3e/0x1a0
[  167.730500]  sock_sendmsg+0x5e/0x60
[  167.730506]  sock_write_iter+0x97/0x100
[  167.730512]  new_sync_write+0x196/0x1b0
[  167.730517]  vfs_write+0x1c3/0x1f0
[  167.730522]  ksys_write+0xa7/0xe0
[  167.730526]  do_syscall_64+0x44/0xc0
[  167.730532]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  167.730535] RIP: 0033:0x7f1661a21fb3
[  167.730540] Code: 75 05 48 83 c4 58 c3 e8 cb 41 ff ff 66 2e 0f 1f 84 00 00 00 00 00 90 64 8b 04 25 18 00 00 00 85 c0 75 14 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 55 c3 0f 1f 40 00 48 83 ec 28 48 89 54 24 18
[  167.730542] RSP: 002b:00007ffd650bfca8 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[  167.730545] RAX: ffffffffffffffda RBX: 000000000000002a RCX: 00007f1661a21fb3
[  167.730547] RDX: 0000000000000036 RSI: 00007ffd650bfcd0 RDI: 0000000000000006
[  167.730549] RBP: 000055913516c490 R08: ffffffff013a0040 R09: ed35307dc900ffff
[  167.730551] R10: 0000ffffffffffff R11: 0000000000000246 R12: 00007ffd650bfcd0
[  167.730552] R13: 000055913463ce90 R14: 00007ffd650c0df0 R15: 00000000000000c8
[  167.730557] ---[ end trace 1a32cb0a9bf4e54d ]---
[  167.730570] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  168.330618] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  168.930651] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  170.670043] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  171.270089] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  171.870124] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  184.606063] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  185.206114] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  185.806152] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  186.450686] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  186.451490] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  186.451580] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  186.451667] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  186.651793] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  186.651906] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  186.652018] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.666924] ath10k_warn: 49 callbacks suppressed
[  189.666931] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.668172] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.668286] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.668394] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.868543] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.868832] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.868942] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  189.869049] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  190.470565] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  190.471938] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  194.741473] ath10k_warn: 58 callbacks suppressed
[  194.741480] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  194.742679] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  194.742794] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  194.742901] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  195.344835] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  195.345118] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  195.346355] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  195.347158] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  195.547344] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  195.548580] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  199.815692] ath10k_warn: 50 callbacks suppressed
[  199.815699] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  199.817020] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  199.817944] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  199.818142] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  200.018340] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  200.018613] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  200.018722] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  200.018830] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  200.218990] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  200.220230] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  204.891838] ath10k_warn: 70 callbacks suppressed
[  204.891845] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  204.892159] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  204.892269] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  204.892377] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  205.092485] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  205.093840] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  205.094019] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  205.094176] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  205.294347] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  205.294887] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  209.911539] ath10k_warn: 78 callbacks suppressed
[  209.911547] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  209.911840] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  209.911947] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  209.912051] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  210.112187] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  210.112479] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  210.112586] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  210.112690] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  210.312841] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  210.312954] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  214.969906] ath10k_warn: 90 callbacks suppressed
[  214.969914] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  214.970028] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  214.970133] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  214.970237] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  215.170347] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  215.170469] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  215.170575] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  215.170679] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  215.370841] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  215.370957] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.026545] ath10k_warn: 90 callbacks suppressed
[  220.026553] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.026840] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.026947] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.027051] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.227191] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.227306] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.227412] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.227516] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.427616] ath10k_pci 0000:02:00.0: failed to transmit frame: -524
[  220.427730] ath10k_pci 0000:02:00.0: failed to transmit frame: -524

**Comment by GetRektBoy724** [comment]
if you guys know how to fix packet injection
pls tell me :)

**Comment by marcost2** [comment]
I dont think it supports it tbh, also please dont open issues for this stuff

**Comment by GetRektBoy724** [comment]
i search a lot in internet...it says that i need a modified firmware for ath10k that supported packet injection
